### ISSUE TITLE
Possibility to dynamically change options

### ISSUE THREAD

**Issue by Deimoslink** [kekeh/mydatepicker#104]
Dear kekeh, first of all, thank you for your job done.

Currently I am trying to implement your datepicker and I faced an interesting issue.
The matter is that I need 2 datepickers in order to have a range.
1st datepicker FROM and 2nd datepicker TO.
Obviously, I want TODatePickerOptions to have an option **disableUntil** which equals the day selected on FROM datepicker.
Unfurtunately, I found out that once **DatePickerOptions** declared, they are not changeable. Thus I tried to bind **disableUntil** to object, which is changed **onDateChanged** and takes the value of **event.data**. However, TO datepicker didn't change its properties. Is it possible to have a method that can refresh **DatePickerOptions**?

It would be great to have a feedback from you.

**Comment by kekeh** [comment]
First of all if you need a date range I have done special component also to it: https://kekeh.github.io/mydaterangepicker/

But you can also use two separate datepicker to that. You can change disableUntil and disableSince options dynamically. Check here **inline** mode: http://kekeh.github.io/mydatepicker/

Source code is here: https://github.com/kekeh/mydatepicker/blob/gh-pages/src/app/components/sample-date-picker-inline/sample-date-picker-inline.ts

In order to mydatepicker detect change of options you have to create new copy of options (in this case **this.myDatePickerOptions**) variable for example:
```javascript
// Returns new copy of options
getCopyOfOptions() {
  return JSON.parse(JSON.stringify(this.myDatePickerOptions));
}
```
and then use new copy of options to set new value to options for example change disableSince
```javascript
let copy = this.getCopyOfOptions();
copy.disableSince =  {year: 2016, month: 11, day: 22};
this.myDatePickerOptions = copy;
```
datepicker detect change of disableSince and the UI of datepicker is updated
