### ISSUE TITLE
Feature request: Required attribute

### ISSUE THREAD

**Issue by MagicMoogle** [kekeh/mydatepicker#119]
Hi, are you able to add a 'required' option to this please that behaves like the normal html required attribute?

**Comment by kekeh** [comment]
**required** attribute is problematic because it is not supported by Safari and also the date picker input field can be editable. Typing one character to the input field set required validation to true in Angular even the date is not valid in input field.

If the purpose of this feature request was a validation there is already solution to that. You can define **inputFieldChanged** callback which informs the host application is date valid or not. Based on that info you can enable/disable submit button or do something else. Check here for more info: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

Sampleapp contains an example of inputFieldCnaged callback: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

**Comment by kekeh** [comment]
Also the option **inputValueRequired** added which can be used to set **required** attribute to the input field.

**Comment by Paldom** [comment]
thanks for quick action!
@kekeh, @MagicMoogle some big news around this issue, Safari will have HTML form validation soon: https://webkit.org/blog/7093/release-notes-for-safari-technology-preview-19/
