### ISSUE TITLE
Setting selDate in function other than constructor

### ISSUE THREAD

**Issue by Zilker-Ztech** [kekeh/mydatepicker#137]
I have initialised selDate as selDate = " ". For me, selDate should be calculated and set onChange of a dropdown. So I have not used in constructor. Instead used in onChange() function.

But an error "dateString.substring is not a function" occurs on page load.

Any suggestion on doing this?

**Comment by kekeh** [comment]
Value of **selDate** attribute can a **string** or an **object**.  

If you use a string alternative the string must be in the same format as your **dateFormat** option is. For example if your dateFormat would be **dd.mm.yyyy** the value of selDate must be **04.01.2017**. Notice prepend zeros if value of the day or the month is lower than 10.

Second alternative is use an object which is easier because you don't need to care about prepend zeros. For example value of selDate could be {year: 2017, month: 1, day: 4}

I think the second alternative would be easier in your case.

README: https://github.com/kekeh/mydatepicker#seldate-attribute
