### ISSUE TITLE
How to empty the content of the input form when the model is empty

### ISSUE THREAD

**Issue by jorgecasariego** [kekeh/mydatepicker#20]
I have  some problems, because I would like to empty the content of the [selDate] with a button, but the content of the input form doesn't change when the content of my [selDate] changes.

```
<my-date-picker [options]="myDatePickerOptions"
               (dateChanged)="onDateChanged($event)"
               [selDate]="selectedDate"></my-date-picker>
```

Do you have any suggestions how to empty the input?

**Comment by kekeh** [comment]
Hi

selDate is intended only to set initial date of date picker. Probably code changes are needed if you want to clear selected date using it.

**Comment by kekeh** [comment]
You can create date picker this way:
`
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)" [selDate]="selectedDate"></my-date-picker>
`

In order to clear the date with an extra button you have to set **this.selectedDate** value in every date selection for example:

`
    onDateChanged(event:any) {
            this.selectedDate = event.formatted;
    }
`

Now you can clear the date with extra button by setting empty string to **this.selectedDate**
