### ISSUE TITLE
inputValueRequired:false property doesn't work properly in ie11

### ISSUE THREAD

**Issue by Aleksei11** [kekeh/mydatepicker#217]
I set inputValueRequired: false
It works in Chrome and Mozilla. But in ie11 it doesn't: http://joxi.ru/4Ak8q65hyVRVjr

**Comment by kekeh** [comment]
If you want that required flag is false you don't need to set any options.

If you want to set required flag to true you can do it as follows:

- Reactive forms: https://github.com/kekeh/mydatepicker#2-reactive-forms
- ngModel binding: https://github.com/kekeh/mydatepicker#3-ngmodel-binding

Here is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

inputValueRequired option is problematic because it does not work in all browsers.
