### ISSUE TITLE
Date Picker disable attribute change when we set date dynamic.

### ISSUE THREAD

**Issue by sudhirroy-tudip** [kekeh/mydatepicker#278]
Hi, When we change date dynamically, disable since taking wrong values. For ex- I set 14/04/2017 and when we reset date to 14/04/2016, then it set 2016 instead of 2017. Kindly help me.

**Comment by kekeh** [comment]
Difficult to say anything without you show how you set disable since and set date dynamically.

**Comment by sudhirroy-tudip** [comment]
ok, For example I set disable since like that 
birthdateDatePickerOptions: IMyOptions= {
 dateFormat: 'mm/dd/yyyy',
 disableUntil: {
      year: new Date().getFullYear() - 101,
      month: new Date().getUTCMonth() + 1, day: new Date().getDate() + 1
    },
    disableSince: {
      year: new Date().getFullYear(),
      month: new Date().getUTCMonth() + 1, day: new Date().getDate() + 1
    }
}
and my template is like this    
<my-date-picker id="my-date-picker" name="birthdate" [options]="birthdateDatePickerOptions"
  readonly  [selDate]="selectedDate" formControlName="birthdate"></my-date-picker>
               
Currently when executing this at starting it disable date after current date (04/25/2017) and before from 101 years.     
 when we set data in [selData]='05/15/2015',  the year button in popup get's disable after 2015 instead of 2017 at starting point.

**Comment by kekeh** [comment]
Because you are using reactive forms the better way to set date dynamically is use **setValue()** function of reactive forms. Here is an example how to use setValue() function: https://github.com/kekeh/mydatepicker#2-reactive-forms (check setDate() function). You can then remove the **selDate** attribute.

Also you can set the values of **disableUntil** and **disableSince** dynamically. Here is an example on how to set disableUntil dynamically: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option 

Hopefully this helps.

**Comment by sudhirroy-tudip** [comment]
I used set value but again when date change, next year button became disabled?

**Comment by kekeh** [comment]
Buttons became disabled if you use **disableUntil** and the previous month is fully disabled or you use **disableSince** and the next month is fully disabled. There is option **disableHeaderButtons** which default is **true**. If you set it to **false** buttons are not disabled like described above.

You cannot do this way: **day: new Date().getDate() + 1**. If date is last day of month (31) then you have problem because you try to set day 32 which is not valid day at all. You need to create function which uses javascript Date to set next day and sets disableUntil for example:
```javascript
disableUntil() {
    let d: date = new Date();
    // set next date
    d.setDate(d.getDate() + 1);

    let copy = this.getCopyOfOptions();
    copy.disableUntil = {year: d.getFullYear() - 101, 
                             month: d.getMonth() + 1, 
                             day: d.getDate()};
    this.myOptions = copy;
}

getCopyOfOptions(): IMyOptions {
    return JSON.parse(JSON.stringify(this.birthdateDatePickerOptions));
}
```
create similar function to disableSince. You can call function for example from the ngOnInit() function.
