### ISSUE TITLE
editableMonthAndYear option removed in version 1.10.0

### ISSUE THREAD

**Issue by kekeh** [kekeh/mydatepicker#285]
Option **editableMonthAndYear** removed. Added options **monthSelector** and **yearSelector**. By default the **monthSelector** and the **yearSelector** are **true**.

If **monthSelector** is **true** a list of months is shown if a month label is clicked. For example:

![month-selector](https://cloud.githubusercontent.com/assets/11028839/25580281/5a7628bc-2e88-11e7-86b2-550ac851deec.png)

If **yearSelector** is **true** a list of years is shown if a year label is clicked. For example:

![year-selector](https://cloud.githubusercontent.com/assets/11028839/25580301/95d08ef2-2e88-11e7-8544-4fcf7c51bf1b.png)

You can set both values to false if you don't need this kind of feature.

You can test functionality here: http://kekeh.github.io/mydatepicker/

**Comment by izub** [comment]
Can you please use semver for versioning? A previous update broke the datepicker for me because some method names were changed, this is unacceptable for a minor version bump.
Also could you have a proper changelog for every release? I don't want to find out there was a breaking change mentioned somewhere in a github issue.
