### ISSUE TITLE
hiding the calendar picker ben

### ISSUE THREAD

**Issue by amitm02** [kekeh/mydatepicker#335]
Awesome project!

how can i hide the calendar picker button and keep only the editable date field?

**Comment by kekeh** [comment]
It is not possible with **mydatepicker**. But if you use **ngx-mydatepicker** it is possible because input box and buttons are your own code.

Repository of ngx-mydatepicker: https://github.com/kekeh/ngx-mydatepicker
Demo of ngx-mydatepicker: https://kekeh.github.io/ngx-mydatepicker

ngx-mydatepicker is looking similar as mydatepicker and options are almost same.
