### ISSUE TITLE
If not required, shouldn't an empty date be valid?

### ISSUE THREAD

**Issue by richardsengers** [kekeh/mydatepicker#346]
If no required attribute is set, and you remove the date from the input field, the valid state is false. Shouldn't that be true?Since the field is not requried.

**Comment by kekeh** [comment]
What valid flag you are referring? Do you mean valid flag of **inputFieldChanged** callback: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

**Comment by richardsengers** [comment]
That's exactly the valid flag I mean :-)

**Comment by kekeh** [comment]
The **inputFieldChanged** callback indicates only is date valid or not in the input box. Empty means no valid date.

You can handle situation to check value of **value** property of the callback. If it is empty string and you have required field you know the date is not valid.

I don't change the functionality because it may cause troubles to other developers.
