### ISSUE TITLE
Unexpected module 'MyDatePickerModule' declared by the module 'AppModule' at SyntaxError.ZoneAwareError

### ISSUE THREAD

**Issue by JiangboLIU** [kekeh/mydatepicker#350]

**Comment by kekeh** [comment]
Did you follow instructions from here: https://github.com/kekeh/mydatepicker#installation

after installation check that following files exists: 
- node_modules/mydatepicker/index.d.ts
- node_modules/mydatepicker/index.js
- node_modules/mydatepicker/package.json (contains line: "version": "2.0.21")

try to reinstall package because in some installations it is invalid:
- npm remove mydatepicker
- npm install mydatepicker --save

**Comment by kekeh** [comment]
Close because no answer.
