### ISSUE TITLE
ng build throws error with angular-cli: 1.0.0-beta.24

### ISSUE THREAD

**Issue by sankaran85** [kekeh/mydatepicker#407]
Hi,
Im getting error "**MyDatePickerModule is not an NgModule**" when i run cmd "ng build" in angular2 environment . 

Im using latest version of datepicker: 2.0.27

Please help me out. Thanks

**Comment by kekeh** [comment]
Probably there are missing files in **node_modules/mydatepicker** folder. There must be the **index.d.ts** file in that folder.

Try to reinstall package:
- npm remove mydatepicker
- npm install mydatepicker --save

Otherwise you have follow instructions from here: https://github.com/kekeh/mydatepicker#installation

List of the **node_modules/mydatepicker** folder:
```javascript
kekeh ~/code/ghpages/mydatepicker/node_modules/mydatepicker $ ls -la
total 64
drwxr-xr-x   4 kekeh kekeh  4096 Aug 12 12:57 .
drwxr-xr-x 746 kekeh kekeh 24576 Aug 12 12:57 ..
drwxr-xr-x   2 kekeh kekeh  4096 Aug 12 12:57 bundles
drwxr-xr-x   5 kekeh kekeh  4096 Aug 12 12:57 dist
-rw-r--r--   1 kekeh kekeh   180 Aug 10 18:16 FONT-LICENSE
-rw-r--r--   1 kekeh kekeh   941 Aug 10 18:16 index.d.ts
-rw-r--r--   1 kekeh kekeh   940 Aug 10 18:16 index.js
-rw-r--r--   1 kekeh kekeh  1072 Aug 10 18:16 LICENSE
-rw-r--r--   1 kekeh kekeh  2299 Aug 12 12:57 package.json
-rw-r--r--   1 kekeh kekeh   975 Aug 10 18:16 README.md
```

**Comment by sankaran85** [comment]
Hi, installed package has all folders you mentioned above and followed the steps u mentioned still i have the issue with latest version.
