### ISSUE TITLE
Hide Extra Rows in Calander 

### ISSUE THREAD

**Issue by shankmr** [kekeh/mydatepicker#427]
I have requirement, that need to hide one extra row that is visible in the calendar with all disabled days. So Is there any work around for this? I know that this is the standard behavior for all the different calendars as well but still it will be helpful if it is possible to do that.

**Comment by kekeh** [comment]
What row do you mean?

**Comment by shankmr** [comment]
If you open calendar for month of Nov, 2017 you will see an extra row with disabled days after 30th Nov.

**Comment by kekeh** [comment]
I want to show always 6 rows, because then selector height is always same. You can click these days and month changes to previous/next month. I don’t have plans to change this functinality and It is not configurable.

I think keeping 6 rows in every month is better because then selector height is not changing When changing a month.
