### ISSUE TITLE
Multiple Datepickers on the Same Page

### ISSUE THREAD

**Issue by wolfhoundjesse** [kekeh/mydatepicker#43]
I'm having an issue where I have two instances of mydatepicker on the same page, and I'm trying to set two different sets of options dynamically. I have a startDate and an endDate, and I want to change the options.disableUntil for endDate whenever the startDate is updated. 

    <mydatepicker [options]="startDateOptions" (dateChanged)="setDate('start', $event)";></mydatepicker>
    <mydatepicker [options]="endDateOptions" (dateChanged)="setDate('end', $event)";></mydatepicker>

On the component, I have this guy that sets the dates well, but it fails to update the second datepicker's options.

    setDate(which: string, date: any){
      switch (which) {
        case 'start': {
          this.form.controls['startDate'].setValue(date.formatted);
          this.setEndDateOptions();
       }
       break;
       ....

    setEndDateOptions(){
      this.endDateOptions.disableUntil = { year: 2017, month: 2, day: 4 }; // for example    
    }

I have checked to make sure that piece of code gets executed, but it doesn't appear to update. I tried forcing changes with ChangeDetectorRef. 

I also noticed that I can't open both datepickers at the same time; opening one closes the other. That is probably because they share a variable name. 

TIA!

**Comment by kekeh** [comment]
If you have one date picker open and you click anywhere on the document, the date picker closes itself because click handler do it.

If I understand you need a **date range** and this https://kekeh.github.io/mydaterangepicker/ component could be then better for that purpose.

But if you want to use two date picker to this purpose you can check sampleapp folder of this project. Date picker in **inline** mode uses **disableUntil** and it sets it value dynamically. https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-inline/sample-date-picker-inline.ts

You can also run the sampleapp. For instructions check this: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by wolfhoundjesse** [comment]
Well, why didn't you say something about this daterangepicker? ;-)

Thank you so much for your quick response. I'll get to work on this now.
