### ISSUE TITLE
well! not working again

### ISSUE THREAD

**Issue by nasreddineskandrani** [kekeh/mydatepicker#44]
second try to integrate your datepicker.

after your update for webpack, doesn't work in my project...how am suppose to integrate this module to my app when i have zero @NgModule in all my code

why a module for your datepicker. it could be (to not say it has to be) a simple "component" !??

**Comment by kekeh** [comment]
Why you are not using NgModule in your app? As you can read from here: https://angular.io/docs/ts/latest/quickstart.html

Step 2: Create your application
=========================
Every Angular application has at least one module: the root module, named AppModule here.

**Comment by nasreddineskandrani** [comment]
am using https://github.com/rangle/angular2-redux-starter

basically this  @NgModule i was introduced in rRC5 and my project was under RC4.

https://github.com/rangle/angular2-redux-example/commit/9d4b02aa20bdb7922f371a8eeb24332e2b480a61

sorry my bad! problem my side. thanks for help i ll give you feedback about the integration after upgrade

**Comment by kekeh** [comment]
Ok. No problem.

**Comment by nasreddineskandrani** [comment]
i tried it and i got this:

> ERROR in ./~/mydatepicker/src/my-date-picker/my-date-picker.module.ts
> Module parse failed: C:\Users\Nasreddine\Desktop\gg\pdaycare-client\node_modules\mydatepicker\src\my-date-picker\my-date-picker.module.ts Unexpected character '@' (6:0)
> You may need an appropriate loader to handle this file type.

**Comment by kekeh** [comment]
At first install latest version of mydatepicker if needed: 
**npm install mydatepicker@0.0.38 -save**

In your own NgModule you can import mydatepicker this way:
**import { MyDatePickerModule } from 'mydatepicker';**

Seems that you have to edit your webpack config file because you got above error. I am not used angular2-redux-started before but maybe you have add mydatepicker to vendor array of this file: https://github.com/rangle/angular2-redux-example/blob/master/webpack.config.js 

or tell webpack other way that it process mydatepicker folder under the node_modules folder. If you check this: https://github.com/rangle/angular2-redux-example/blob/master/webpack/loaders.js. The ts-loader excludes the node_modules folder by default.

**Comment by zanattaman** [comment]
I'm having the same issue and adding it to the webpack configuration does not help. Any other solution?

**Comment by kekeh** [comment]
@nasreddineskandrani 

Did you solve this issue? Ans how?
